var oQ_0={
Qid:1,
Qtype:'MultipleChoice',
QDifficiulty:'1',
QPointValue:'5',
Question:'Who is here?',
Qid:1,
OpenBookService:'',
CorrectAnsFlag:false,
Score:0,
Took_rem:false,
QuestionBookMarked:0,
Remediation:[],
RemediationViewed:[],
IncorrectRemediationService:'',
CorrectRemediationService:'',
Do_It_Later:'',
answered:'',
UserResponseStatus:'',
QTotalResponse:4,
Qresp0:'You',
QAns0:'',
Qresp1:'Me',
QAns1:'',
Qresp2:'No one.',
QAns2:'',
Qresp3:'Everyone',
QAns3:'',
InCorrectRemediation:[['You',''],['Me',''],['No one.',''],['Everyone','']],
Qrightanswer0:'No one.',
QTotalRightAnswer:1,
ENDQ:''};